# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: special_course.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14special_course.proto\x12\x0especial_course\"\x17\n\x07Request\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x18\n\x05Reply\x12\x0f\n\x07message\x18\x01 \x01(\t2F\n\x07Greeter\x12;\n\x05query\x12\x17.special_course.Request\x1a\x15.special_course.Reply\"\x00\x30\x01\x42+Z)dtu.com/grpc/golang/special_course/protosb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'special_course_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z)dtu.com/grpc/golang/special_course/protos'
  _REQUEST._serialized_start=40
  _REQUEST._serialized_end=63
  _REPLY._serialized_start=65
  _REPLY._serialized_end=89
  _GREETER._serialized_start=91
  _GREETER._serialized_end=161
# @@protoc_insertion_point(module_scope)
