# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import special_course_pb2 as special__course__pb2


class ServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDevices = channel.unary_unary(
                '/special_course.Server/GetDevices',
                request_serializer=special__course__pb2.Empty.SerializeToString,
                response_deserializer=special__course__pb2.Devices.FromString,
                )
        self.GetDetailsOfDevice = channel.unary_unary(
                '/special_course.Server/GetDetailsOfDevice',
                request_serializer=special__course__pb2.Interface.SerializeToString,
                response_deserializer=special__course__pb2.InterfaceDetails.FromString,
                )
        self.ServerStreaming = channel.unary_stream(
                '/special_course.Server/ServerStreaming',
                request_serializer=special__course__pb2.Interface.SerializeToString,
                response_deserializer=special__course__pb2.StreamReply.FromString,
                )


class ServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDetailsOfDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerStreaming(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDevices,
                    request_deserializer=special__course__pb2.Empty.FromString,
                    response_serializer=special__course__pb2.Devices.SerializeToString,
            ),
            'GetDetailsOfDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDetailsOfDevice,
                    request_deserializer=special__course__pb2.Interface.FromString,
                    response_serializer=special__course__pb2.InterfaceDetails.SerializeToString,
            ),
            'ServerStreaming': grpc.unary_stream_rpc_method_handler(
                    servicer.ServerStreaming,
                    request_deserializer=special__course__pb2.Interface.FromString,
                    response_serializer=special__course__pb2.StreamReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'special_course.Server', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Server(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/special_course.Server/GetDevices',
            special__course__pb2.Empty.SerializeToString,
            special__course__pb2.Devices.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDetailsOfDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/special_course.Server/GetDetailsOfDevice',
            special__course__pb2.Interface.SerializeToString,
            special__course__pb2.InterfaceDetails.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ServerStreaming(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/special_course.Server/ServerStreaming',
            special__course__pb2.Interface.SerializeToString,
            special__course__pb2.StreamReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
